config/routes.rb
Rails.application.routes.draw do

  resources :publishers
  namespace :admin do
    resources :authors
  end
  get 'about/index'

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/author.rb
class Admin::Author < ActiveRecord::Base
  has_and_belongs_to_many :books
  validates_presence_of :first_name, :last_name
  def name
    "#{first_name} #{last_name}"
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_and_belongs_to_many :authors
  belongs_to :publisher
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  has_many :books
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = "About emporium";
  end
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController
  before_action :set_admin_author, only: [:show, :edit, :update, :destroy]

  # GET /admin/authors
  # GET /admin/authors.json
  def index
    @admin_authors = Admin::Author.all
    @page_title = 'Listing authors'
  end

  # GET /admin/authors/1
  # GET /admin/authors/1.json
  def show
    @author = Admin::Author.find(params[:id])
    @page_title = @author.name
  end

  # GET /admin/authors/new
  def new
    @admin_author = Admin::Author.new
    @page_title = 'Create new author'
  end

  # GET /admin/authors/1/edit
  def edit
  end

  # POST /admin/authors
  # POST /admin/authors.json
  def create
    @admin_author = Admin::Author.new(admin_author_params)

    respond_to do |format|
      if @admin_author.save
        format.html { redirect_to @admin_author, notice: 'Author #{@author.name} was successfully created.' }
        format.json { render :show, status: :created, location: @admin_author }
      else
        format.html { render :new }
        format.json { render json: @admin_author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/authors/1
  # PATCH/PUT /admin/authors/1.json
  def update
    respond_to do |format|
      if @admin_author.update(admin_author_params)
        format.html { redirect_to @admin_author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_author }
      else
        format.html { render :edit }
        format.json { render json: @admin_author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/authors/1
  # DELETE /admin/authors/1.json
  def destroy
    @admin_author.destroy
    respond_to do |format|
      format.html { redirect_to admin_authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_author
      @admin_author = Admin::Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_author_params
      params.require(:admin_author).permit(:first_name, :last_name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, notice: 'Publisher was successfully created.' }
        format.json { render :show, status: :created, location: @publisher }
      else
        format.html { render :new }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishers/1
  # PATCH/PUT /publishers/1.json
  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to @publisher, notice: 'Publisher was successfully updated.' }
        format.json { render :show, status: :ok, location: @publisher }
      else
        format.html { render :edit }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher.destroy
    respond_to do |format|
      format.html { redirect_to publishers_url, notice: 'Publisher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publisher_params
      params.require(:publisher).permit(:publisher)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/authors_helper.rb
module Admin::AuthorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/admin/authors/_form.html.erb
<%= form_for(@admin_author) do |f| %>
  <% if @admin_author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_author.errors.count, "error") %> prohibited this admin_author from being saved:</h2>

      <ul>
      <% @admin_author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/authors/edit.html.erb
<h1>Editing Admin Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_author %> |
<%= link_to 'Back', admin_authors_path %>

app/views/admin/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Admin Authors</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_authors.each do |admin_author| %>
      <tr>
        <td><%= admin_author.first_name %></td>
        <td><%= admin_author.last_name %></td>
        <td><%= link_to 'Show', admin_author %></td>
        <td><%= link_to 'Edit', edit_admin_author_path(admin_author) %></td>
        <td><%= link_to 'Destroy', admin_author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_admin_author_path %>

app/views/admin/authors/new.html.erb
<h1>New Admin Author</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_authors_path %>

app/views/admin/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @admin_author.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @admin_author.last_name %>
</p>

<%= link_to 'Edit', edit_admin_author_path(@admin_author) %> |
<%= link_to 'Back', admin_authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || 'Emporium' %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/publishers/_form.html.erb
<%= form_for(@publisher) do |f| %>
  <% if @publisher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
      <% @publisher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :publisher %><br>
    <%= f.text_field :publisher %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publishers/edit.html.erb
<h1>Editing Publisher</h1>

<%= render 'form' %>

<%= link_to 'Show', @publisher %> |
<%= link_to 'Back', publishers_path %>

app/views/publishers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Publishers</h1>

<table>
  <thead>
    <tr>
      <th>Publisher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publishers.each do |publisher| %>
      <tr>
        <td><%= publisher.publisher %></td>
        <td><%= link_to 'Show', publisher %></td>
        <td><%= link_to 'Edit', edit_publisher_path(publisher) %></td>
        <td><%= link_to 'Destroy', publisher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Publisher', new_publisher_path %>

app/views/publishers/new.html.erb
<h1>New Publisher</h1>

<%= render 'form' %>

<%= link_to 'Back', publishers_path %>

app/views/publishers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Publisher:</strong>
  <%= @publisher.publisher %>
</p>

<%= link_to 'Edit', edit_publisher_path(@publisher) %> |
<%= link_to 'Back', publishers_path %>